# Generated by Django 4.0.4 on 2022-05-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=500)),
                ('LastName', models.CharField(max_length=500)),
                ('PhoneNumber', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=254)),
                ('Department', models.CharField(max_length=500)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiters',
            fields=[
                ('RecruiterId', models.AutoField(primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=500)),
                ('PhoneNumber', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=254)),
                ('Department', models.CharField(max_length=500)),
                ('JobTitle', models.CharField(max_length=500)),
                ('Requirements', models.CharField(max_length=500)),
                ('NumberofDevelopers', models.CharField(max_length=250)),
                ('DateOfApplication', models.DateField()),
                ('FileName', models.CharField(max_length=500)),
            ],
        ),
    ]
