# Generated by Django 4.0.4 on 2022-05-25 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_recruiters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiters',
            old_name='County',
            new_name='Department',
        ),
    ]
